apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rrr.fullname" . }}-frontend
  labels:
    {{- include "rrr.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "rrr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "rrr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.images.frontend.repository }}:{{ .Values.images.frontend.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: API_UPSTREAM
              value: "http://{{ include "rrr.fullname" . }}-api:{{ .Values.api.service.port }}"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "rrr.fullname" . }}-frontend
  labels:
    {{- include "rrr.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "rrr.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.service.port }}
      targetPort: 80
