apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rrr.fullname" . }}-data
  labels:
    {{- include "rrr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.storage.size }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "rrr.fullname" . }}-postgres
  labels:
    {{- include "rrr.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgres.storage }}
