apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rrr.fullname" . }}-worker
  labels:
    {{- include "rrr.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      {{- include "rrr.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: worker
  template:
    metadata:
      labels:
        {{- include "rrr.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: worker
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: worker
          image: "{{ .Values.images.worker.repository }}:{{ .Values.images.worker.tag }}"
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: {{ include "rrr.fullname" . }}-config
            - secretRef:
                name: {{ include "rrr.fullname" . }}-secret
          volumeMounts:
            - name: data
              mountPath: {{ .Values.storage.mountPath }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "rrr.fullname" . }}-data
